[custom]

; 启用自定义规则
enable_rule_generator=true

; 覆盖订阅原本自带的规则，只保留下面两条
overwrite_original_rules=true

; 中国大陆 IP 直连
ruleset=DIRECT,[]GEOIP,CN

; 其余流量进入 Final
ruleset=Final,[]FINAL

; 创建 Final 策略组，包含全部节点
custom_proxy_group=Final`select`.*
