[custom]

enable_rule_generator=true
overwrite_original_rules=true

; 中国大陆 IP 直连
ruleset=DIRECT,[]GEOIP,CN

; 其余流量走“节点选择”
ruleset=🎯 节点选择,[]FINAL

; 创建“节点选择”策略组，包含全部节点
custom_proxy_group=🎯 节点选择`select`.*
